// <auto-generated />
using System;
using BGClima.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BGClima.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250730192304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BGClima.Domain.Entities.AirConditioner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AirConditionerTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasInverter")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasWiFi")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("NoiseLevel")
                        .HasColumnType("numeric");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("integer");

                    b.Property<int>("WarrantyMonths")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AirConditionerTypeId");

                    b.HasIndex("BrandId");

                    b.HasIndex("SeriesId");

                    b.ToTable("AirConditioners");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.AirConditionerCategory", b =>
                {
                    b.Property<int>("AirConditionerId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("AirConditionerId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("AirConditionerCategories");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.AirConditionerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AirConditionerTypes");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.AirFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirConditionerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AirConditionerId")
                        .IsUnique();

                    b.ToTable("AirFlows");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Filter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirConditionerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AirConditionerId")
                        .IsUnique();

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AirConditionerId")
                        .HasColumnType("integer");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AirConditionerId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Installation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirConditionerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AirConditionerId")
                        .IsUnique();

                    b.ToTable("Installations");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirConditionerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AirConditionerId")
                        .IsUnique();

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirConditionerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AirConditionerId")
                        .IsUnique();

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirConditionerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPromo")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceValue")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AirConditionerId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeatures");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Specification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AirConditionerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AirConditionerId");

                    b.ToTable("Specifications");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Warranty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirConditionerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AirConditionerId")
                        .IsUnique();

                    b.ToTable("Warranties");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.AirConditioner", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.AirConditionerType", "AirConditionerType")
                        .WithMany("AirConditioners")
                        .HasForeignKey("AirConditionerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BGClima.Domain.Entities.Brand", "Brand")
                        .WithMany("AirConditioners")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BGClima.Domain.Entities.Series", "Series")
                        .WithMany("AirConditioners")
                        .HasForeignKey("SeriesId");

                    b.Navigation("AirConditionerType");

                    b.Navigation("Brand");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.AirConditionerCategory", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.AirConditioner", "AirConditioner")
                        .WithMany("AirConditionerCategories")
                        .HasForeignKey("AirConditionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BGClima.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirConditioner");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.AirFlow", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.AirConditioner", "AirConditioner")
                        .WithOne("AirFlow")
                        .HasForeignKey("BGClima.Domain.Entities.AirFlow", "AirConditionerId");

                    b.Navigation("AirConditioner");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Filter", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.AirConditioner", "AirConditioner")
                        .WithOne("Filter")
                        .HasForeignKey("BGClima.Domain.Entities.Filter", "AirConditionerId");

                    b.Navigation("AirConditioner");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Image", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.AirConditioner", "AirConditioner")
                        .WithMany("Images")
                        .HasForeignKey("AirConditionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirConditioner");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Installation", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.AirConditioner", "AirConditioner")
                        .WithOne("Installation")
                        .HasForeignKey("BGClima.Domain.Entities.Installation", "AirConditionerId");

                    b.Navigation("AirConditioner");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Operation", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.AirConditioner", "AirConditioner")
                        .WithOne("Operation")
                        .HasForeignKey("BGClima.Domain.Entities.Operation", "AirConditionerId");

                    b.Navigation("AirConditioner");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Performance", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.AirConditioner", "AirConditioner")
                        .WithOne("Performance")
                        .HasForeignKey("BGClima.Domain.Entities.Performance", "AirConditionerId");

                    b.Navigation("AirConditioner");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Price", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.AirConditioner", null)
                        .WithMany("Prices")
                        .HasForeignKey("AirConditionerId");

                    b.HasOne("BGClima.Domain.Entities.Product", "Product")
                        .WithOne("Price")
                        .HasForeignKey("BGClima.Domain.Entities.Price", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Product", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.ProductFeature", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.Product", "Product")
                        .WithMany("Features")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Series", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.Brand", "Brand")
                        .WithMany("Series")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Specification", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.AirConditioner", "AirConditioner")
                        .WithMany("Specifications")
                        .HasForeignKey("AirConditionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirConditioner");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Stock", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.Product", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("BGClima.Domain.Entities.Stock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Warranty", b =>
                {
                    b.HasOne("BGClima.Domain.Entities.AirConditioner", "AirConditioner")
                        .WithOne("Warranty")
                        .HasForeignKey("BGClima.Domain.Entities.Warranty", "AirConditionerId");

                    b.Navigation("AirConditioner");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.AirConditioner", b =>
                {
                    b.Navigation("AirConditionerCategories");

                    b.Navigation("AirFlow")
                        .IsRequired();

                    b.Navigation("Filter")
                        .IsRequired();

                    b.Navigation("Images");

                    b.Navigation("Installation")
                        .IsRequired();

                    b.Navigation("Operation")
                        .IsRequired();

                    b.Navigation("Performance")
                        .IsRequired();

                    b.Navigation("Prices");

                    b.Navigation("Specifications");

                    b.Navigation("Warranty")
                        .IsRequired();
                });

            modelBuilder.Entity("BGClima.Domain.Entities.AirConditionerType", b =>
                {
                    b.Navigation("AirConditioners");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Brand", b =>
                {
                    b.Navigation("AirConditioners");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Product", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Images");

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Stock")
                        .IsRequired();
                });

            modelBuilder.Entity("BGClima.Domain.Entities.Series", b =>
                {
                    b.Navigation("AirConditioners");
                });
#pragma warning restore 612, 618
        }
    }
}
